language: node_js

node_js:
  - 8

jobs:
  include:
    - stage: test
      script: npm run test:cov-report
    - stage: build
      script: npm run build
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release --debug
